### ISSUE TITLE
Zod for serialization and deserialization data

### ISSUE THREAD

**Issue by listepo** [connectrpc/connect-es#1233] opened 2024-09-13 23:34 UTC
Hello any way to support serialization and deserialization data for [zod](https://github.com/colinhacks/zod) schema?

**Comment by timostamm** [comment] 2024-09-17 10:00
Hey Ivan, we looked into decoupling serialization from connect-es for #1030. The Connect protocol is agnostic to serialization, so it's technically possible, and we don't have any interest in artificially limiting the implementation. 

We found that it's far from trivial to support, though. All options we considered ended up requiring much more boilerplate to set up, ultimately making the developer experience considerable worse. Hopefully we can implement the feature at some point, but we currently aren't actively working on it.

**Comment by timostamm** [comment] 2024-10-17 12:51
Closing this as a duplicate of #1030.

**Closed by timostamm** 2024-10-17 12:51 UTC
Labels: enhancement
