### ISSUE TITLE
CancelFn isn't cancelling the stream with Expo 52

### ISSUE THREAD

**Issue by hollanderbart** [connectrpc/connect-es#1363] opened 2024-12-05 15:41 UTC
**Describe the bug**

When I've created a `createCallbackClient` callback client, and I created a stream, a `CancelFn` will be returned. If I want to cancel this function, the stream isn't cancelled.

**To Reproduce**

- Create a callback client
- Setup a stream
- Wait until the first message arrives
- After the first message has arrived, try to cancel the stream
- Stream is still continuing 

**Environment (please complete the following information):**

Connectrpc/connect in combination with React Native

```js
unsubscribeRef.current = deviceClientCallback.streamDevice(
...,
(messageResponse: StreamDeviceResponse) => {
   unsubscribeRef.current() //this will not cancel the stream
})
unsubscribeRef.current() //this will cancel the stream, only before the first message has arrived. 
```

**Comment by hollanderbart** [comment] 2024-12-05 15:43
@timostamm Can you please help me here? Maybe I'm just doing something wrong here. But it seems that after receiving a message, will make the `abort` / `cancel` invalid.

**Comment by srikrsna-buf** [comment] 2024-12-05 17:21
Hey @hollanderbart Can you share a reproducible example? We do have a [test](https://github.com/connectrpc/connect-es/blob/main/packages/connect-conformance/src/callback-client.ts#L149) that checks for this case.

**Comment by hollanderbart** [comment] 2024-12-05 17:26
Not yet. I can create one tomorrow. Is there a public stream call I can use?

I think it's a race condition because after the first message arrived, the cancel isn't working.

**Comment by srikrsna-buf** [comment] 2024-12-05 17:49
> Is there a public stream call I can use?

Yes, you use [this](https://buf.build/connectrpc/eliza/docs/main:connectrpc.eliza.v1#connectrpc.eliza.v1.ElizaService.Introduce) rpc hosted at `https://demo.connectrpc.com`



> I'm sure the test will do something, but does it check if the stream is cancelled on the network level?

It indirectly checks it by validating the responses it is supposed to receive. We also pass the signal to `fetch`.

**Comment by hollanderbart** [comment] 2024-12-06 15:16
Repo: https://github.com/hollanderbart/BusinessCards-Connect

The logs that it print is:

```
 (NOBRIDGE) LOG  {"$typeName": "connectrpc.eliza.v1.IntroduceResponse", "sentence": "Hi John Doe. I'm Eliza."}
 (NOBRIDGE) LOG  Eliza introduce stream connected
 (NOBRIDGE) LOG  Trying to cancel the stream
 (NOBRIDGE) LOG  {"$typeName": "connectrpc.eliza.v1.IntroduceResponse", "sentence": "Before we begin, John Doe, let me tell you something about myself."}
 (NOBRIDGE) LOG  Eliza introduce stream connected
 (NOBRIDGE) LOG  Trying to cancel the stream
 (NOBRIDGE) LOG  {"$typeName": "connectrpc.eliza.v1.IntroduceResponse", "sentence": "I was one of the first programs capable of attempting the Turing test."}
 (NOBRIDGE) LOG  Eliza introduce stream connected
 (NOBRIDGE) LOG  Trying to cancel the stream
 (NOBRIDGE) LOG  {"$typeName": "connectrpc.eliza.v1.IntroduceResponse", "sentence": "How are you feeling today?"}
 (NOBRIDGE) LOG  Eliza introduce stream connected
 (NOBRIDGE) LOG  Trying to cancel the stream
 (NOBRIDGE) LOG  [FastEncoder] (assureJSILoaded) JSI install: Installed
 (NOBRIDGE) ERROR  undefined
```

**Comment by hollanderbart** [comment] 2024-12-09 09:21
Or is the need for a custom Transport necessary? Can the React Native example app please updated using the latest `expo/fetch` implementation? @timostamm Thanks!

https://github.com/connectrpc/examples-es/blob/cd9a4d1b3bc069b13a907880511b7cbb49cfb965/react-native/app/custom-transport.ts

**Comment by timostamm** [comment] 2024-12-09 13:10
Hey Bart, for a very long time, React Native didn't implement `fetch`, only `XMLHttpRequest`. That's why we added the custom transport as an example. It implements gRPC-Web unary calls via `XMLHttpRequest`.

I'm very happy that RN finally has `fetch`. This means it will be possible to use server-streaming RPCs via the Connect or gRPC-Web protocols, in addition to unary RPCs. Updating the example is tracked in https://github.com/connectrpc/examples-es/issues/2134.

If the CancelFn returned by the callback client doesn't abort the request in RN, this is a bug in the fetch implementation of RN / expo, since we continually run tests asserting that it does, on various web browsers and Node.js.

Can you try to reproduce the problem with a minimal example that uses `fetch` directly, and file the issue against expo?

**Comment by hollanderbart** [comment] 2024-12-09 20:42
I've changed my repo to implement a simple [httpbin stream](https://github.com/hollanderbart/BusinessCards-Connect).

Also I've created an issue report on the Expo repo.

**Comment by chrispine** [comment] 2024-12-13 17:11
I'm going to go ahead and close this, but feel free to reopen if needed

**Closed by chrispine** 2024-12-13 17:11 UTC
