### ISSUE TITLE
Use the Fetch with ReadableStream to support request streams in the Connect for Web.

### ISSUE THREAD

**Issue by gartz** [connectrpc/connect-es#599] opened 2023-05-01 00:40 UTC
**Is your feature request related to a problem? Please describe.**
Use the bytes feature to upload files from the browser to the server using request stream.

**Describe the solution you'd like**
Connect for Web : Add support to request stream using `ReadableStream` instance being passed to the request `body`.

**Describe alternatives you've considered**
If you've proposed a solution, are there any alternatives? Why are they worse
than your preferred approach?
Using unary. It's worse because large files it quite loads the client and server memory. Also there is no way to implement resuming upload when using unary calls.

**Comment by timostamm** [comment] 2024-09-09 13:35
I'll close this as a duplicate of #669, which has a bit more details.

**Closed by timostamm** 2024-09-09 13:35 UTC
Labels: enhancement
