### ISSUE TITLE
[Question?] cache key failed to generate on Next.js app router

### ISSUE THREAD

**Issue by mnpqraven** [connectrpc/connect-es#914] opened 2023-11-08 13:29 UTC
**Is your feature request related to a problem? Please describe.**
I'm relatively new to Connect and have been following the tutorial to implement rpc in my Next.js app.
Considering the following
```
export function rpc<T extends ServiceType>(service: T): PromiseClient<T> {
  const client = createPromiseClient(
    service,
    createGrpcWebTransport({
      baseUrl: "https://randomurl.com",
    })
  );
  return client;
}
```
I'm getting cache errors from next saying that caching for this call failed (hsr.dev is my nextjs app and nas-ws is my rust backend server with the rpc endpoints)
![image](https://github.com/connectrpc/connect-es/assets/8957788/10fe17da-55b0-46d7-98d9-6f1c27b3c058)

**Describe the solution you'd like**
I was wondering if this is a misconfiguration on my part or caching is not yet supported for Next.js, or if caching rpc is not possible in general

**Comment by srikrsna-buf** [comment] 2023-11-08 14:21
I am not familiar with nextjs caching strategy but my guess is that it doesn't support post requests and grpc web works on post

**Comment by srikrsna-buf** [comment] 2023-11-09 13:51
I can confirm that cache only applies to GET requests from this [doc](https://nextjs.org/docs/app/building-your-application/caching). The connect protocol supports [GET requests](https://connectrpc.com/docs/web/get-requests-and-caching), if you can switch to connect protocol then GET requests (and therefore caching) can be enabled on a per rpc basis.

Let us know if you run into any problems, closing this for now feel free reach out if I missed something.

**Closed by srikrsna-buf** 2023-11-09 13:51 UTC
Labels: enhancement

**Comment by arpitBhalla** [comment] 2024-05-17 05:16
I'm calling `GET` requests, but caching doesn't work for me
![image](https://github.com/connectrpc/connect-es/assets/55053424/6bf31025-9592-41d8-a8dd-a6eea8da16ed)


```ts
export const fetchInfo = cache(async (id: string) => {
    return await client.getInfo({id});
});
```

```ts
export async function generateMetadata({params, searchParams}: PageProps) {
    const insight = await fetchInfo(params.id);
    return generateInsightMetadata(insight);
}
```

**Comment by srikrsna-buf** [comment] 2024-05-20 11:44
If you are using the `cache` function it shouldn't matter if it is a get/post request. Does the error also tell you why it failed to create the cache key?

**Comment by edigaryev** [comment] 2024-09-13 12:53
> If you are using the `cache` function it shouldn't matter if it is a get/post request. Does the error also tell you why it failed to create the cache key?

I've encountered this when bootstrapping Connect RPC on Next.js and it seems to be a bug in the Next.js-patched `fetch()` that treats `Uint8Array` request bodies as `FormData`/`URLSearchParams` when trying to calculate the cache key (yeah, it does calculate the key even through that `POST` request is not going to be cached).

See https://github.com/vercel/next.js/pull/70065 for more details.
